version: '3.8'

services:
  farm-admin-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: farm-admin-app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4200:4200"
    networks:
     - app_network

networks:
  app_network:
    driver: bridge